info:
  app:
    name: clickstream-service
    description: clickstream

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8109

spring:  

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

clickstream:
    neo4jDb: http://localhost:7474/db/data

---
spring:
    profiles: docker

server:
    port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/