info:
  app:
    name: catalog-recommendation-service
    description: Recommends catalog items to the user

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8109

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

recommendation:
    neo4jHost: http://localhost:7474/

---
spring:
    profiles: docker

server:
    port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

recommendation:
    neo4jHost: http://neo4j:7474/